"""Policy data used by the deterministic resume/JD scoring engine."""

CATEGORY_WEIGHTS = {
    "Must-have requirements": 0.35,
    "Preferred requirements": 0.15,
    "Experience and seniority": 0.20,
    "Domain and tools fit": 0.20,
    "Evidence quality": 0.10,
}

STOP_WORDS = {
    "a",
    "about",
    "across",
    "an",
    "and",
    "are",
    "as",
    "be",
    "by",
    "for",
    "from",
    "in",
    "is",
    "it",
    "of",
    "on",
    "or",
    "our",
    "that",
    "the",
    "their",
    "this",
    "to",
    "with",
    "work",
    "will",
    "you",
}

GENERIC_REQUIREMENT_WORDS = {
    "ability",
    "background",
    "candidate",
    "communication",
    "detail",
    "driven",
    "excellent",
    "experience",
    "familiarity",
    "good",
    "knowledge",
    "layers",
    "management",
    "models",
    "pipelines",
    "preferred",
    "proficiency",
    "productionize",
    "required",
    "responsibilities",
    "role",
    "scaling",
    "serving",
    "skills",
    "strong",
    "systems",
    "team",
    "teams",
    "understanding",
    "working",
}

MUST_HAVE_MARKERS = (
    "required",
    "must",
    "minimum",
    "need",
    "needs",
    "responsibilities",
    "requirements",
    "qualifications",
)

PREFERRED_MARKERS = (
    "preferred",
    "nice to have",
    "bonus",
    "plus",
    "desired",
)

JD_SECTION_HEADINGS = {
    "about",
    "about the job",
    "about the company",
    "about the role",
    "about us",
    "basic qualifications",
    "benefits",
    "company",
    "compensation",
    "culture",
    "equal opportunity",
    "equal opportunity employer",
    "how to apply",
    "job description",
    "job attributes",
    "key responsbilities",
    "key responsibilities",
    "nice to have",
    "nice-to-have",
    "our ethos",
    "about the team",
    "overview",
    "perks",
    "preferred qualifications",
    "preferred requirements",
    "qualifications",
    "required qualifications",
    "required skills",
    "requirements",
    "responsibilities",
    "role overview",
    "salary",
    "skills",
    "skills and experience",
    "the role",
    "what you'll do",
    "what we do",
    "what we offer",
    "what we're looking for",
    "what we are looking for",
    "what you bring",
    "what you will do",
    "who we are",
    "why join us",
    "you will",
    "you are likely to succeed if you have",
    "your responsibilities",
}

LOW_SIGNAL_DIRECT_TERMS = {
    "ai",
    "applied ai",
    "automation",
    "cloud",
    "infrastructure",
    "machine learning",
    "ml",
    "monitoring",
    "platform",
    "production",
    "reliability",
}

NON_REQUIREMENT_LINE_STARTS = (
    "at ",
    "about ",
    "as a company",
    "if you're curious",
    "if you are curious",
    "join us",
    "our ",
    "primarily, you like",
    "the company",
    "today,",
    "we are ",
    "we believe ",
    "we're ",
    "we re ",
)

VAGUE_CULTURE_LINES = {
    "you show more than you tell",
    "you show more than you tell.",
    "primarily, you like to make great things with passionate colleagues",
    "primarily, you like to make great things with passionate colleagues.",
}

REQUIREMENT_ACTION_PATTERNS = (
    r"\bability to\b",
    r"\bable to\b",
    r"\bbuild(?:ing)?\b",
    r"\bdebug(?:ging)?\b",
    r"\bdeploy(?:ing)?\b",
    r"\bdesign(?:ing)?\b",
    r"\bdevelop(?:ing)?\b",
    r"\bexperience (?:with|in|building|managing|operating|using)\b",
    r"\bfamiliar(?:ity)? with\b",
    r"\bimplement(?:ing)?\b",
    r"\bmaintain(?:ing)?\b",
    r"\bmanage(?:ing|d)?\b",
    r"\boperate(?:ing|d)?\b",
    r"\bown(?:ing)?\b",
    r"\bproficien(?:t|cy) (?:with|in)\b",
    r"\bresponsible for\b",
    r"\btroubleshoot(?:ing)?\b",
    r"\byou (?:have|bring|can|will|are able to)\b",
)

IGNORED_JD_SECTION_HEADINGS = {
    "about",
    "about the job",
    "about the company",
    "about us",
    "about the team",
    "benefits",
    "company",
    "compensation",
    "culture",
    "equal opportunity",
    "equal opportunity employer",
    "how to apply",
    "job attributes",
    "our ethos",
    "overview",
    "perks",
    "salary",
    "what we do",
    "what we offer",
    "who we are",
    "why join us",
}

JD_METADATA_LABELS = {
    "application deadline",
    "apply by",
    "compensation",
    "department",
    "employment type",
    "job attributes",
    "job level",
    "job location",
    "location",
    "number of openings",
    "openings",
    "salary",
    "salary range",
    "start date",
    "target start date",
    "work arrangement",
    "work location",
    "work mode",
}

DOMAIN_TERMS = {
    "agency",
    "ai",
    "banking",
    "cloud",
    "compliance",
    "cost",
    "cybersecurity",
    "data",
    "devops",
    "enterprise",
    "finance",
    "finops",
    "healthcare",
    "infrastructure",
    "latency",
    "linux",
    "marketplace",
    "monitoring",
    "network",
    "platform",
    "recruiting",
    "security",
    "trading",
}

SENIORITY_TERMS = {
    "principal": 90,
    "staff": 85,
    "lead": 78,
    "senior": 72,
    "architect": 72,
    "manager": 68,
    "mid": 55,
    "junior": 35,
    "entry": 25,
}

AFFIRMATIVE_ACTION_VERBS = (
    "achieved",
    "analyzed",
    "architected",
    "automated",
    "built",
    "created",
    "delivered",
    "designed",
    "developed",
    "documented",
    "drove",
    "implemented",
    "improved",
    "led",
    "managed",
    "owned",
    "prepared",
    "presented",
    "reconciled",
    "researched",
    "supported",
)

ENTERPRISE_SCOPE_TERMS = (
    "asc 606",
    "audit",
    "auditors",
    "consolidated",
    "cross-functionally",
    "emea",
    "external audit",
    "financial statements",
    "fp&a",
    "gaap financial statements",
    "global",
    "ifrs",
    "international subsidiaries",
    "latam",
    "leadership",
    "mentor",
    "multi-entity",
    "operationalize",
    "policies and procedures",
    "regulatory",
    "revenue contracts",
    "statutory",
    "technical accounting",
    "technical accounting positions",
)

GENERIC_BOOKKEEPING_TERMS = (
    "ap/ar",
    "bank reconciliation",
    "basic gaap",
    "bookkeeping",
    "expense coding",
    "invoice processing",
    "payroll",
    "quickbooks",
    "small business",
    "tax preparation",
    "vendor records",
)

DOMAIN_QUALIFIER_RULES = (
    {
        "name": "software_sales",
        "action_terms": ("account manager", "account management", "sales", "selling", "sold", "quota", "revenue"),
        "qualifier_terms": ("software", "saas", "b2b software", "cloud software", "enterprise software"),
    },
    {
        "name": "saas_revenue_accounting",
        "action_terms": ("accounting", "revenue", "revenue recognition", "financial reporting", "close"),
        "qualifier_terms": ("saas", "asc 606", "subscription", "deferred revenue", "revenue contracts"),
    },
    {
        "name": "software_project_management",
        "action_terms": ("project management", "project manager", "managed projects", "program management"),
        "qualifier_terms": ("software", "agile", "scrum", "engineering", "development team", "sdlc"),
    },
    {
        "name": "technical_support",
        "action_terms": ("customer service", "support", "helped customers", "resolved issues"),
        "qualifier_terms": ("technical", "troubleshoot", "hardware", "software", "help desk", "it support"),
    },
    {
        "name": "clinical_ehr",
        "action_terms": ("healthcare", "clinical", "patient", "medical records", "records"),
        "qualifier_terms": ("ehr", "emr", "electronic health records", "epic", "cerner", "clinical software"),
    },
    {
        "name": "low_latency_trading_infrastructure",
        "action_terms": ("infrastructure", "linux", "server", "systems administration", "performance tuning"),
        "qualifier_terms": ("low latency", "low-latency", "trading", "deterministic", "clock synchronization", "ptp"),
    },
)
